apiVersion: v1
kind: Secret
metadata:
  namespace: n8n
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: ${POSTGRES_USER:?Set POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Set POSTGRES_PASSWORD}
  POSTGRES_DB: n8n
  POSTGRES_NON_ROOT_USER: ${POSTGRES_NON_ROOT_USER:?Set POSTGRES_NON_ROOT_USER}
  POSTGRES_NON_ROOT_PASSWORD: ${POSTGRES_NON_ROOT_PASSWORD:?Set POSTGRES_NON_ROOT_PASSWORD}
