http_port 3128
visible_hostname squid-proxy

cache_mem 256 MB
cache_dir ufs /var/spool/squid 100 16 256
access_log /var/log/squid/access.log
cache_log /var/log/squid/cache.log
coredump_dir /var/spool/squid

# AUTH
auth_param basic program /usr/lib/squid/basic_ncsa_auth /etc/squid/auth/passwd
auth_param basic realm Proxy
acl authenticated proxy_auth REQUIRED

# ALLOW
http_access allow authenticated
http_access deny all

