# https://www.smarthomebeginner.com/portainer-docker-compose-guide/
version: "3.9"

services:

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    command: -H unix:///var/run/docker.sock 
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro 
      - ./appdata/portainer/data:/data 
    environment:
      - TZ=$TZ
